### ISSUE TITLE
`fold_left`, `fold_right` and `fmap` do not work with a lazy function

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#942] opened 2019-04-10 20:09 UTC
Having the following code:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float32"
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(func):
    return func.eval()
	
@Phylanx
def map_fn_eager(fn, elems, dtype):
	return fmap(fn, elems)

def map_fn(fn, elems, name=None, dtype=None):
	return map_fn_eager.lazy(fn, elems, dtype)
	
@Phylanx
def sum_eager(x, axis=None, keepdims=False):
	return np.sum(x, axis, keepdims)

def sum(x, axis=None, keepdims=False):
	return sum_eager.lazy(x, axis, keepdims)
	
	
def test_map():
	x = [1,2,3]
	vx = variable(x)
	kx = eval(map_fn(sum, vx))
	return kx

test_map()
```
results in:
```pytb
Traceback (most recent call last):
  File "test51.py", line 63, in <module>
    print(test_map())
  File "test51.py", line 47, in test_map
    kx = eval(foldl(sum, vx))
  File "test51.py", line 41, in foldl
    return foldl_eager.lazy(fn, elems, initializer)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 123, in lazy
    return self.backend.lazy(map(self.map_decorated, args))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 526, in lazy
    return self.eval_wrapper(self, tuple(map(self.map_wrapped, args)))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 111, in map_decorated
    fn_physl = PhySL(val, fn_ast, {})
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 387, in __init__
    self.ir = self.apply_rule(tree.body[0])
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 434, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 951, in _FunctionDef
    body = self.block(node.body)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 440, in block
    block = tuple(map(self.apply_rule, node))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 434, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 1144, in _Return
    value = self.apply_rule(node.value)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 434, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 693, in _Call
    symbol = self.apply_rule(node.func)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 434, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 654, in _Attribute
    'Cannot transform: %s' % attr)
NotImplementedError: Phylanx does not support non-NumPy member functions.Cannot transform: sum_eager.lazy
```

**Comment by taless474** [comment] 2019-10-17 19:30
Would anyone please take a look at this?
`fmap`, `fold_right` and `fold_left` do not work on Numpy function, either.
```python
from phylanx import Phylanx, PhylanxSession, execution_tree
import numpy as np

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float64"
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)

def eval(x):
	return x.eval()

	
@Phylanx
def map_fn_eager(fn, elems):
	return fmap(fn, elems)

def map_fn(fn, elems, dtype=None):
	return variable(map_fn_eager(fn, elems),dtype=dtype)
	
elems = variable(np.array([1,0,1,1,0,1,0,0]))

map_fn(np.sum,elems)
```
results in
```pytb
Traceback (most recent call last):
  File "test8.py", line 38, in <module>
    map_fn(np.sum,elems)
  File "test8.py", line 34, in map_fn
    return variable(map_fn_eager(fn, elems),dtype=dtype)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 151, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 123, in map_decorated
    fn_physl = PhySL(val, fn_ast, self.kwargs)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 414, in __init__
    self.ir = self.apply_rule(tree.body[0])
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 467, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 976, in _FunctionDef
    body = self.block(node.body)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 473, in block
    block = tuple(map(self.apply_rule, node))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 467, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 1003, in _If
    body = self.block(node.body)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 473, in block
    block = tuple(map(self.apply_rule, node))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 467, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 898, in _Expr
    return self.apply_rule(node.value)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 467, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 731, in _Call
    symbol = self.apply_rule(node.func)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 467, in apply_rule
    return eval('self._%s' % node_name)(node)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 692, in _Attribute
    'Cannot transform: %s' % attr)
NotImplementedError: Phylanx does not support non-NumPy member functions.Cannot transform: warnings.warn
```

**Comment by hkaiser** [comment] 2019-10-21 22:32
@taless474 I think we can't do anything for the second example you provided, but the first one can be fixed by writing:
```
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
    if dtype is None:
        dtype = "float32"
    if constraint is not None:
        raise TypeError("Constraint is the projection function to be "
                        "applied to the variable after an optimizer update")
    from phylanx.ast.physl import PhySL
    if isinstance(value, PhySL.eval_wrapper):
        return execution_tree.variable(value.code(), dtype)
    if isinstance(value, execution_tree.variable):
        return value
    return execution_tree.variable(value, dtype=dtype, name=name)

def eval(func):
    return func.eval()

@Phylanx
def map_fn_eager(fn, elems, dtype):
    return fmap(fn, elems)

def map_fn(fn, elems, name=None, dtype=None):
    return map_fn_eager.lazy(fn, elems, dtype)

@Phylanx
def sum_eager(x, axis=None, keepdims=False):
    return np.sum(x, axis, keepdims)

def sum(x, axis=None, keepdims=False):
    return sum_eager.lazy(x, axis, keepdims)

def test_map():
    x = [1, 2, 3]
    vx = variable(x)
    kx = eval(map_fn(sum_eager, vx))
    return kx

print(test_map())
```
(note the use of `sum_eager`) - not sure if this helps, though...

**Comment by taless474** [comment] 2019-10-21 23:45
Thank you.
In the backend_test we need to call `K.sum` and I think we cannot use the eager form of it. Do we need to write a different `map`?

**Comment by hkaiser** [comment] 2019-10-22 02:05
Here is an idea. The issue is that we need to pass a python function to one of our `@Phylanx` decorated functions that does nothing more than representing a lazy evaluation of a `@Phylanx` decorated one. There is no way to detect that from plain python code.

We could however create a separate decorator for this:
```
@Phylanx
def map_fn_eager(fn, elems, dtype):
    return fmap(fn, elems)

@Phylanx.lazy
def map_fn(fn, elems, name=None, dtype=None):
    return fmap(fn, elems)

@Phylanx
def sum_eager(x, axis=None, keepdims=False):
    return np.sum(x, axis, keepdims)

@Phylanx.lazy
def sum(x, axis=None, keepdims=False):
    return np.sum(x, axis, keepdims)
```
which would do the same thing as before except that `sum` now represents a special type that can be detected in the same way as we detect the type represented by `map_fn_eager`. This would enable special handling of cases like:
```
map_fn(sum, variable([1, 2, 3]))
```
Let's talk about this in more detail.

**Comment by hkaiser** [comment] 2019-10-22 09:14
@taless474 I think we can do even better by enabling:
```
@Phylanx
def map_fn_eager(fn, elems, dtype=None):
    return fmap(fn, elems)

map_fn = Phylanx.lazy(map_fn_eager)

@Phylanx
def sum_eager(x, axis=None, keepdims=False):
    return np.sum(x, axis, keepdims)

sum = Phylanx.lazy(sum_eager)
```
This would avoid the pointless code duplication.

**Comment by hkaiser** [comment] 2019-10-22 10:04
I think #1058 resolves this issue, please verify. Also, this simplifies defining lazy functions (a lot!). There is however no need to go back and change all existing lazy functions, only if you need to pass those to other decorated functions like in your `fn_map(sum, ...)` example above. 

FWIW, the new functionality:
```
sum = Phylanx.lazy(sum_eager)
```
is functionally equivalent to what we've had before:
```
def sum(*args, **kwargs):
    return sum_eager.lazy(*args, **kwargs)
```
just now `sum` can be passed to another decorated `@Phylanx` function.

**Comment by taless474** [comment] 2019-10-22 15:54
```python
from phylanx import Phylanx, PhylanxSession, execution_tree
import numpy as np

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
    if dtype is None:
        dtype = "float32"
    if constraint is not None:
        raise TypeError("Constraint is the projection function to be "
                        "applied to the variable after an optimizer update")
    from phylanx.ast.physl import PhySL
    if isinstance(value, PhySL.eval_wrapper):
        return execution_tree.variable(value.code(), dtype)
    if isinstance(value, execution_tree.variable):
        return value
    return execution_tree.variable(value, dtype=dtype, name=name)

def eval(func):
    return func.eval()


@Phylanx
def map_fn_eager(fn, elems, dtype=None):
    return fmap(fn, elems)

map_fn = Phylanx.lazy(map_fn_eager)

@Phylanx
def sum_eager(x, axis=None, keepdims=False):
    print(x)
    return np.sum(x, axis, keepdims)

sum = Phylanx.lazy(sum_eager)

elems = variable(np.array([1,0,1,1,0,1,0,0]))

def test_map():
    x = np.array([[1, 2, 3]])
    vx = variable(x)
    kx = eval(map_fn(sum, vx))
    return kx

print(test_map())
```
results in:
```pytb
[1, 2, 3]
Traceback (most recent call last):
  File "test13.py", line 44, in <module>
    print(test_map())
  File "test13.py", line 41, in test_map
    kx = eval(map_fn(sum, vx))
  File "test13.py", line 20, in eval
    return func.eval()
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 508, in eval
    *self.args, **self.kwargs)
RuntimeError: test13.py(25, 11): fmap:: the invoked lambda returned an unexpected type (should be a vector value): HPX(bad_parameter)
```
expected result:
```pytb
array([6.], dtype=float32)
```

**Closed** 2019-10-24 18:23 UTC
Labels: category: @Phylanx, type: compatibility issue, type: defect
