### ISSUE TITLE
Phylanx does not allow assignment to a slice

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#575] opened 2018-08-28 17:13 UTC
This code throws an error, it should instead set matrix element 0,0.
```py
from phylanx import Phylanx
import numpy as np

a = np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]])

@Phylanx
def f1(a):
    a[0:1,0:1]=8
    print(a)

f1(a)
```

**Comment by stevenrbrandt** [comment] 2018-08-29 14:11
The generated PhySL is this
```
define(
    f1,
    a,
    block(
        store(
            slice(
                a,
                list(0, 1),
                list(0, 1)
            ),
            8
        ),
        cout(a)
    )
)
```
It does not call the appropriate set operation.

**Comment by stevenrbrandt** [comment] 2018-08-29 14:11
In case you like tracebacks....
```
Traceback (most recent call last):
  File "f.py", line 14, in <module>
    f1(a)
  File "/root/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/ast/transducer.py", line 77, in __call__
    return self.backend.call(args)
  File "/root/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/ast/physl.py", line 164, in call
    *args)
RuntimeError: <unknown>(11, 4): slice:: store function should only be called for the primitives that support it (e.g. variables): HPX(invalid_status)
```

**Comment by rtohid** [comment] 2018-08-29 15:03
The `set` primitive is not used anymore as its functionality has been moved to `store`. 
The error is caused by the assignment to the function argument which is not supported, please see the link in my last comment.

**Comment by hkaiser** [comment] 2018-08-30 02:09
The simplest workaround is to assign the argument to a local variable and use that instead:
```
@Phylanx
def f1(arg):
    a = arg
    a[0:1,0:1]=8
    print(a)
```

**Comment by hkaiser** [comment] 2018-09-06 19:26
This is a duplicate of #540

**Closed by hkaiser** 2018-09-06 19:26 UTC
Labels: category: PhySL, category: primitives, submodule: frontend, tag: duplicate, type: compatibility issue
