### ISSUE TITLE
Can't define arg at the start of a for loop

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#226] opened 2018-02-16 23:21 UTC
```
import phylanx
et = phylanx.execution_tree

et.eval("""
block(define(sum, block(
    define(n,0),
    for(store(n,3),n < 10,store(n,n+1),
        block(cout(n))
    ),
    n)), sum)
""")

# However, this should work, too
et.eval("""
block(define(sum, block(
    for(define(n,3),n < 10,store(n,n+1),
        block(cout(n))
    ),
    n)), sum)
""")
```
Output
```
3
4
5
6
7
8
9
RuntimeError: couldn't find given name in symbol table: n: HPX(bad_parameter)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "q.py", line 21, in <module>
    """)
SystemError: <built-in method eval of PyCapsule object at 0x7f13867302d0> returned a result with an error set
```

**Comment by hkaiser** [comment] 2018-02-17 00:27
@stevenrbrandt this is an interesting scoping issue. The question is whether the `define(n, 3)` is visible in it's own scope only or in the wider scope of the `for()` statement. Making it visible in the `for()` scope would mean extending it's visibility beyond it's actual scope. 

I'm not sure if that's what we want as it would require for `define()` to behave differently depending on whether it's used as the first argument in a `for()` or not.

**Comment by hkaiser** [comment] 2018-02-17 12:40
@stevenrbrandt after thinking about this more I agree with you that the issue you reported is a bug. This needs to be fixed.

**Comment by hkaiser** [comment] 2018-02-19 23:49
@stevenrbrandt this is not a bug after all. You define `n` in the scope of the `for()` statement, so it's visibility is constrained to that. Then you refer to `n` _after_ the `for`, at which point it has gone out of scope. If you need the variable outside of the `for` scope it needs to be defined outside as well. This is similar to how things are done in C/C++:
```
for (int n = 3; n < 10; n = n + 1)
{
    cout << n << '\n';
}
// 'n' is not usable here anymore
```

**Comment by stevenrbrandt** [comment] 2018-02-21 17:09
OK, I see what you mean. However, if we replace the "n" outside the loop with a "1" , we still have the same error.
```
import phylanx
et = phylanx.execution_tree

et.eval("""
block(define(sum, block(
    define(n,0),
    for(store(n,3),n < 10,store(n,n+1),
        block(cout(n))
    ),
    1)), sum)
""")

# However, this should work, too
et.eval("""
block(define(sum, block(
    for(define(n,3),n < 10,store(n,n+1),
        block(cout(n))
    ),
    1)), sum)
""")
```

**Comment by hkaiser** [comment] 2018-02-21 20:26
Now it complains about a different issue: `primitive_argument_type does not hold a literal value type`. This is a real issue which I will address.

**Comment by stevenrbrandt** [comment] 2018-02-21 20:30
Sorry, yes, it is a different error. This was the error I meant to report.

**Closed** 2018-02-22 15:21 UTC
Labels: category: PhySL, type: defect
