### ISSUE TITLE
Primitives needed for ALS algorithm

### ISSUE THREAD

**Issue by scheherzad** [STEllAR-GROUP/phylanx#145] opened 2018-01-11 21:47 UTC
- [x] Identity matrix similar to numpy.identity
- [ ] Elementwise comparison similar to numpy
- [ ] return a matrix with the input vector on its diagonal, similar to numpy.diag

**Comment by hkaiser** [comment] 2018-01-15 16:16
This is a duplicate of #35. Closing this.

**Closed by hkaiser** 2018-01-15 16:16 UTC
Labels: tag: duplicate
