### ISSUE TITLE
Rerunning a PhySL Python function does not work

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#375] opened 2018-04-27 20:36 UTC
Code to reproduce
```python
@Phylanx()
def fx():
    print(12)
    return 0
```
Which returns `12` (it should not run at all). If `fx()` is run again():
```python
fx()
```
The output is:
`0`
It should have printed 12

**Comment by hkaiser** [comment] 2018-04-27 23:34
This is a duplicate of #340.

**Closed by hkaiser** 2018-04-27 23:34 UTC
Labels: category: @Phylanx, tag: duplicate, type: defect
