### ISSUE TITLE
Having a variable on both sides of an assignment.

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#348] opened 2018-04-11 17:38 UTC
Running 
```
@Phylanx()
def add(a, b):
    a = a + b
    return a

print(add(2, 3))
```
will cause the following error:
"RuntimeError: <unknown>: access-argument$0$a/0$49$4:: store function should only be called for the 
primitives that support it (e.g. variables): HPX(invalid_status)" 

Replacing the `a` on the left-hand side with a new variable resolves the issue, so, the following works fine:
```
@Phylanx()
def add(a, b):
    c = a + b
    return c

print(add(2, 3))
```

**Comment by hkaiser** [comment] 2018-04-11 22:33
As you said, the issue is not having a variable but having a function argument on the left hand side of the expression. A possible workaround for now would be to store the argument in a local variable before assigning:

    @Phylanx()
    def add (a, b):
        c = a
        c = c + b
        return c

**Comment by hkaiser** [comment] 2018-04-26 17:45
This is a duplicate of #320

**Closed by hkaiser** 2018-04-26 17:45 UTC
Labels: category: PhySL, submodule: backend, type: defect
