### ISSUE TITLE
python transducer throws NotImplementedError on return

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#889] opened 2019-03-20 19:10 UTC
In [physl_ldahyper.py](https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/algorithms/lda/physl_ldahyper.py) on line 90 (`return EULER_MASCHERONI - invZ`), Phylanx's python transducer throws a `NotImplementedError: Illegal return: line=90, col=8`. The exception occurs in phylanx/ast/physl.py:258, in check_noreturn.

note: physl_ldahyper.py needs to have some modifications checked into the repository before it can be tested. The phylanx import command needs to be fixed and all the method calls to .shape, need to be replaced with np.shape calls.

**Comment by hkaiser** [comment] 2019-03-20 22:36
@stevenrbrandt any comments?

**Comment by hkaiser** [comment] 2019-04-21 16:20
This is a duplicate of #888. Closing.

**Closed by hkaiser** 2019-04-21 16:20 UTC
Labels: compiler: python, submodule: frontend, type: defect
