### ISSUE TITLE
tangent integration

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#19] opened 2017-09-08 03:08 UTC
Test Python bindings for interoperability with SymPy.

**Comment by ct-clmsn** [comment] 2018-02-21 18:01
@hkaiser @stevenrbrandt do ya'll mind if this ticket is changed from sympy to tangent? tangent provides the specific capability that we originally aimed to inherit from sympy (auto-differentiation).

**Comment by stevenrbrandt** [comment] 2018-02-21 20:24
@ct-clmsn, Do we want to limit ourselves to auto-differentiation? I'm not clear on the pros and cons of SymPy  vs. Tangent at the moment.

**Comment by hkaiser** [comment] 2018-12-26 13:36
This is a duplicate of #225. Closing...

**Closed by hkaiser** 2018-12-26 13:36 UTC
Labels: submodule: frontend, submodule: middleware, tag: duplicate
